export const FETCH_DOCUMENTOS_REQUEST = 'FETCH_DOCUMENTOS_REQUEST';
export const FETCH_DOCUMENTOS_SUCCESS = 'FETCH_DOCUMENTOS_SUCCESS';
export const FETCH_DOCUMENTOS_FAILURE = 'FETCH_DOCUMENTOS_FAILURE';

export const PRINT_DOCUMENTO_REQUEST = 'PRINT_DOCUMENTO_REQUEST';
export const PRINT_DOCUMENTO_SUCCESS = 'PRINT_DOCUMENTO_SUCCESS';
export const PRINT_DOCUMENTO_FAILURE = 'PRINT_DOCUMENTO_FAILURE';

export const FETCH_LOJAS_REQUEST = 'FETCH_LOJAS_REQUEST';
export const FETCH_LOJAS_SUCCESS = 'FETCH_LOJAS_SUCCESS';
export const FETCH_LOJAS_FAILURE = 'FETCH_LOJAS_FAILURE';

export const FETCH_TABLOIDES_REQUEST = 'FETCH_TABLOIDES_REQUEST';
export const FETCH_TABLOIDES_SUCCESS = 'FETCH_TABLOIDES_SUCCESS';
export const FETCH_TABLOIDES_FAILURE = 'FETCH_TABLOIDES_FAILURE';

export const FETCH_PAPEIS_REQUEST = 'FETCH_PAPEIS_REQUEST';
export const FETCH_PAPEIS_SUCCESS = 'FETCH_PAPEIS_SUCCESS';
export const FETCH_PAPEIS_FAILURE = 'FETCH_PAPEIS_FAILURE';

export const FETCH_TIPOS_REQUEST = 'FETCH_TIPOS_REQUEST';
export const FETCH_TIPOS_SUCCESS = 'FETCH_TIPOS_SUCCESS';
export const FETCH_TIPOS_FAILURE = 'FETCH_TIPOS_FAILURE';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_REQUEST_DENIED = 'SIGNIN_REQUEST_DENIED';
export const SIGNIN_REQUEST_SUCCESS = 'SIGNIN_REQUEST_SUCCESS';
export const SIGNIN_REQUEST_FAILURE = 'SIGNIN_REQUEST_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REQUEST_REFRESHED_TOKEN = 'REQUEST_REFRESHED_TOKEN';
export const REFRESHED_TOKEN_SUCCESS = 'REFRESHED_TOKEN_SUCCESS';
export const REFRESHED_TOKEN_FAILURE = 'REFRESHED_TOKEN_FAILURE';

export const GET_LOJAS_REQUEST = 'GET_LOJAS_REQUEST';
export const GET_LOJAS_SUCCESS = 'GET_LOJAS_SUCCESS';
export const GET_LOJAS_FAILURE = 'GET_LOJAS_FAILURE';

export const UNLOAD_DOCUMENTOS_REQUEST = 'UNLOAD_DOCUMENTOS_REQUEST';
export const UNLOAD_DOCUMENTOS_SUCCESS = 'UNLOAD_DOCUMENTOS_SUCCESS';
export const UNLOAD_DOCUMENTOS_FAILURE = 'UNLOAD_DOCUMENTOS_FAILURE';
